---
- name: Install and Configure HTTPD
  hosts: all
  become: yes

  tasks:
    - name: Install HTTPD
      yum:
        name: httpd
        state: present

    - name: Create test index page
      copy:
        content: "Welcome from AWX"
        dest: /var/www/html/index.html
      notify:
        - Restart HTTPD

    - name: Start HTTPD
      service:
        name: httpd
        state: started
        enabled: yes

  handlers:
    - name: Restart HTTPD
      service:
        name: httpd
        state: restarted
